name: PyrexEPFix
version: '2.0'
main: org.pyrex.pyrexepfix.PyrexEPFix
api-version: '1.20'
commands:
  pyrexepfix:
    description: Reload the PyrexEPFix plugin
    usage: /<command>
    permission: pyrexepfix.admin